server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      timeout: 50000
      host: localhost

jwt:
  access:
    key: ${KEY_ACCESS}
    expire: 3600

  refresh:
    key: ${KEY_REFRESH}
    expire: 7200


